SOURCES = [
    {
        "name": "Львівська політехніка",
        "level": 1,
        "type": "html",
        "url": "https://lpnu.ua/news",
        "link_pattern": r"^/news/[^/]+$",
        "max_items": 40,
    },
    {
        "name": "ZAXID.NET",
        "level": 1,
        "type": "html",
        "url": "https://zaxid.net/",
        "link_pattern": r"_n\\d+$",
        "max_items": 50,
    },
    {
        "name": "Твоє Місто",
        "level": 1,
        "type": "html",
        "url": "https://tvoemisto.tv/uk/news",
        "link_pattern": r"^/uk/news/\\d+-",
        "max_items": 50,
    },
    {
        "name": "Львівський портал",
        "level": 1,
        "type": "html",
        "url": "https://portal.lviv.ua/news",
        "link_pattern": r"^/news/\\d{4}/\\d{2}/\\d{2}/",
        "max_items": 50,
    },
    {
        "name": "Вголос",
        "level": 1,
        "type": "html",
        "url": "https://vgolos.ua/news/",
        "link_pattern": r"^/news/.+_\\d+\\.html$",
        "max_items": 50,
    },
    {
        "name": "Варіанти",
        "level": 1,
        "type": "html",
        "url": "https://varianty.lviv.ua/",
        "link_pattern": r"^/publikatsiyi/",
        "max_items": 50,
    },
    {
        "name": "Дивись.info",
        "level": 1,
        "type": "html",
        "url": "https://dyvys.info/news/",
        "link_pattern": r"^/\\d{4}/\\d{2}/\\d{2}/",
        "max_items": 50,
    },
    {
        "name": "Українські Новини",
        "level": 2,
        "type": "html",
        "url": "https://ukranews.com/ua/news?lang=ua",
        "link_pattern": r"^/ua/news/\\d+-",
        "max_items": 60,
    },
]
